[[language]]
name = "javascript"
scope = "source.js"
injection-regex = "(js|javascript)"
language-id = "javascript"
file-types = ["js", "mjs", "cjs", "rules", "es6", "pac", { glob = ".node_repl_history" }, { glob = "jakefile" }]
shebangs = ["node"]
roots = [ "package.json" ]
language-servers = [
  "eslint",
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "typescript"
scope = "source.ts"
injection-regex = "(ts|typescript)"
language-id = "typescript"
file-types = ["ts", "mts", "cts"]
shebangs = ["deno", "bun", "ts-node"]
roots = [ "package.json", "tsconfig.json" ]
language-servers = [
  "eslint",
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "tsx"
scope = "source.tsx"
injection-regex = "(tsx)" # |typescript
language-id = "typescriptreact"
file-types = ["tsx"]
roots = ["package.json", "tsconfig.json"]
language-servers = [
  "eslint",
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
