session = "carsten-fuehrmanns-blog"

[open]

# terminal = [] 
# terminal = ["alacritty", "--command"]
# terminal = ["kitty"]
# terminal = [ "foot", "--" ]
# terminal = [ "footclient", "--" ]
# terminal = ["wezterm", "start", "--"]

[find]
# hidden-method = "picker"
